# -*- mode: python ; coding: utf-8 -*-
"""PyInstaller spec for the DeskPulse macOS app (.app bundle).

Must be built ON macOS (PyInstaller cannot cross-compile a Mac app from Windows).
Produces dist/DeskPulse.app, which build_mac.sh wraps into a .dmg.

    pyinstaller agent/packaging/deskpulse_mac.spec --noconfirm
"""
import os

HERE = os.path.abspath(SPECPATH)             # agent/packaging
ICON = os.path.join(HERE, "icon.icns")       # generated by build_mac.sh if missing

hiddenimports = [
    "pynput.keyboard._darwin", "pynput.mouse._darwin",
    "mss", "PIL.Image", "PIL.ImageFilter",
]

REPO = os.path.abspath(os.path.join(HERE, "..", ".."))

a = Analysis(
    [os.path.join(REPO, "run_deskpulse.py")],
    pathex=[REPO],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    excludes=["tkinter", "matplotlib", "numpy", "pytest"],
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data)

exe = EXE(
    pyz, a.scripts, [], exclude_binaries=True,
    name="DeskPulse", debug=False, strip=False, upx=False, console=False,
    icon=ICON if os.path.exists(ICON) else None,
)
coll = COLLECT(exe, a.binaries, a.zipfiles, a.datas, strip=False, upx=False, name="DeskPulse")

app = BUNDLE(
    coll,
    name="DeskPulse.app",
    icon=ICON if os.path.exists(ICON) else None,
    bundle_identifier="com.deskpulse.agent",
    info_plist={
        "CFBundleName": "DeskPulse",
        "CFBundleDisplayName": "DeskPulse",
        "CFBundleShortVersionString": "1.0.0",
        "CFBundleVersion": "1.0.0",
        "LSUIElement": False,            # show in Dock (set True for tray-only)
        "NSHighResolutionCapable": True,
        # macOS will prompt the user to grant these — required for monitoring.
        "NSAppleEventsUsageDescription": "DeskPulse tracks active windows while you track time.",
    },
)
